version: '3.8'

services:
  # MongoDB Service
  mongodb:
    image: mongo
    container_name: i-love-mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongodb_data:/data/db
    networks:
      - research-agent-network
    restart: unless-stopped

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: research-agent-api
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
    environment:
      - MONGODB_URL=mongodb://admin:password@mongodb:27017
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - ./:/app
    networks:
      - research-agent-network
    restart: unless-stopped

networks:
  research-agent-network:
    driver: bridge

volumes:
  mongodb_data: